---

- name: RKE2 agent and server tasks
  include_role:
    name: rke2_common
    tasks_from: main

- name: Add server url to config file
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ kubernetes_api_server_host }}:9345"

- name: Add token to config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars[groups['rke2_servers'][0]].rke2_config_token }}"

- name: Start rke2-agent
  systemd:
    name: rke2-agent.service
    state: started
    enabled: yes
    daemon_reload: yes
